spring.application.name=grievance-track

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/grievance_track
spring.datasource.username=root
spring.datasource.password=Mothi@7305314158

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086